---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Try installing GNOME Gedit
      become: true
      community.general.flatpak:
        name: org.gnome.gedit
        state: present
        method: system

...
